/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef INITIALISER_PRIVATE_H
#define INITIALISER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.662"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	662
#define COMPANY_NAME	"Himvan"
#define FILE_VERSION	"1.0.0.662"
#define FILE_DESCRIPTION	"Minesweeper"
#define INTERNAL_NAME	"MS 1.0"
#define LEGAL_COPYRIGHT	"Copyright 2013. Shobhit Saxena"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Minesweeper"
#define PRODUCT_VERSION	"1.0.0.662"

#endif /*INITIALISER_PRIVATE_H*/
